# Generated by Django 6.0.2 on 2026-03-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creake', '0005_cakerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='review_count',
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cakes/'),
        ),
    ]
