# Generated by Django 6.0.2 on 2026-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creake', '0007_order_received_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
