# Generated by Django 6.0.2 on 2026-04-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creake', '0007_course_student'),
        ('creake', '0009_cakereview'),
    ]

    operations = [
    ]
