# Generated by Django 6.0.2 on 2026-04-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creake', '0010_merge_0007_course_student_0009_cakereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
